// 22 Scheduled Languages of India + English translation dictionary
export interface LanguageTranslation {
  arenaControl: string;
  fanCompanion: string;
  analytics: string;
  commandTitle: string;
  liveBroadcast: string;
  gamedayMode: string;
  recentIntercom: string;
  activeFans: string;
  staffMesh: string;
  emergencyAlert: string;
  vipArrival: string;
  metroMalfunction: string;
  stepFree: string;
  launchAr: string;
  simulateLoad: string;
  slipFall: string;
}

export const INDIAN_LANGUAGES = [
  { code: 'en', name: 'English', nativeName: 'English' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी' },
  { code: 'bn', name: 'Bengali', nativeName: 'বাংলা' },
  { code: 'te', name: 'Telugu', nativeName: 'తెలుగు' },
  { code: 'mr', name: 'Marathi', nativeName: 'मराठी' },
  { code: 'ta', name: 'Tamil', nativeName: 'தமிழ்' },
  { code: 'ur', name: 'Urdu', nativeName: 'اردو' },
  { code: 'gu', name: 'Gujarati', nativeName: 'ગુજરાતી' },
  { code: 'kn', name: 'Kannada', nativeName: 'ಕನ್ನಡ' },
  { code: 'ml', name: 'Malayalam', nativeName: 'മലയാളം' },
  { code: 'or', name: 'Odia', nativeName: 'ଓଡ଼ିଆ' },
  { code: 'pa', name: 'Punjabi', nativeName: 'ਪੰਜਾਬੀ' },
  { code: 'as', name: 'Assamese', nativeName: 'অসমীয়া' },
  { code: 'ma', name: 'Maithili', nativeName: 'मैथिली' },
  { code: 'sa', name: 'Sanskrit', nativeName: 'संस्कृतम्' },
  { code: 'ks', name: 'Kashmiri', nativeName: 'کٲشور' },
  { code: 'ne', name: 'Nepali', nativeName: 'नेपाली' },
  { code: 'ko', name: 'Konkani', nativeName: 'कोंकणी' },
  { code: 'sd', name: 'Sindhi', nativeName: 'सिन्धी' },
  { code: 'dog', name: 'Dogri', nativeName: 'डोगरी' },
  { code: 'mni', name: 'Manipuri', nativeName: 'মৈতৈলোন' },
  { code: 'bod', name: 'Bodo', nativeName: 'बर\'' },
  { code: 'sat', name: 'Santali', nativeName: 'संताली' }
];

export const TRANSLATIONS: Record<string, LanguageTranslation> = {
  en: {
    arenaControl: "Arena Control Center",
    fanCompanion: "Fan Companion",
    analytics: "Overview & Analytics",
    commandTitle: "Estadio Azteca Command",
    liveBroadcast: "LIVE BROADCAST",
    gamedayMode: "GAMEDAY MODE",
    recentIntercom: "Recent Intercom Log",
    activeFans: "Fan App Sync: 84,212 Active",
    staffMesh: "Staff Comms: 1,204 Linked",
    emergencyAlert: "Emergency Weather Alert",
    vipArrival: "VIP Delegation Arrival",
    metroMalfunction: "Post-Match Metro Malfunction",
    stepFree: "Step-Free Accessibility Routing",
    launchAr: "Launch AR Camera Wayfinder",
    simulateLoad: "Simulate 84k Load Spike",
    slipFall: "Slip & Fall Detected"
  },
  hi: {
    arenaControl: "एरिना नियंत्रण केंद्र",
    fanCompanion: "प्रशंसक साथी ऐप",
    analytics: "अवलोकन और विश्लेषण",
    commandTitle: "एस्टाडियो एज़्टेका कमांड",
    liveBroadcast: "सजीव प्रसारण",
    gamedayMode: "खेल का दिन",
    recentIntercom: "हालिया इंटरकॉम लॉग",
    activeFans: "सक्रिय प्रशंसक: 84,212",
    staffMesh: "स्टाफ मेश नेटवर्क: 1,204",
    emergencyAlert: "आपातकालीन मौसम चेतावनी",
    vipArrival: "वीआईपी प्रतिनिधिमंडल आगमन",
    metroMalfunction: "मैच के बाद मेट्रो खराबी",
    stepFree: "सीढ़ी-मुक्त सुलभ मार्ग",
    launchAr: "एआर कैमरा मार्गदर्शक शुरू करें",
    simulateLoad: "84k लोड स्पाइक का अनुकरण करें",
    slipFall: "फिसलने और गिरने का पता चला"
  },
  bn: {
    arenaControl: "অ্যারেনা কন্ট্রোল সেন্টার",
    fanCompanion: "ফ্যান কম্প্যানিয়ন",
    analytics: "ওভারভিউ এবং অ্যানালিটিক্স",
    commandTitle: "এস্তাদিও অ্যাজটেকা কমান্ড",
    liveBroadcast: "সরাসরি সম্প্রচার",
    gamedayMode: "খেলার দিন মোড",
    recentIntercom: "সাম্প্রতিক ইন্টারকম লগ",
    activeFans: "সক্রিয় ফ্যান: ৮৪,২১২",
    staffMesh: "স্টাফ জাল নেটওয়ার্ক: ১,২০৪",
    emergencyAlert: "জরুরী আবহাওয়া সতর্কতা",
    vipArrival: "ভিআইপি প্রতিনিধি আগমন",
    metroMalfunction: "ম্যাচ-পরবর্তী মেট্রো বিভ্রাট",
    stepFree: "ধাপ-মুক্ত অ্যাক্সেসযোগ্য রাউটিং",
    launchAr: "এআর ক্যামেরা ওয়েফাইন্ডার চালু করুন",
    simulateLoad: "84k লোড স্পাইক সিমুলেট করুন",
    slipFall: "পিছলে পড়ে যাওয়া শনাক্ত করা হয়েছে"
  },
  te: {
    arenaControl: "అరేనా నియంత్రణ కేంద్రం",
    fanCompanion: "ఫ్యాన్ కంపానియన్",
    analytics: "అవలోకనం & విశ్లేషణలు",
    commandTitle: "ఎస్టాడియో అజ్టెకా కమాండ్",
    liveBroadcast: "లైవ్ ప్రసారం",
    gamedayMode: "గేమ్‌డే మోడ్",
    recentIntercom: "ఇంటర్కామ్ లాగ్స్",
    activeFans: "కనెక్ట్ అయిన అభిమానులు: 84,212",
    staffMesh: "సిబ్బంది మెష్ నెట్వర్క్: 1,204",
    emergencyAlert: "వాతావరణ హెచ్చరిక",
    vipArrival: "VIP డెలిగేషన్ రాక",
    metroMalfunction: "మెట్రో అంతరాయం",
    stepFree: "మెట్లు లేని సులభ మార్గం",
    launchAr: "AR కెమెరా ప్రారంభించండి",
    simulateLoad: "84k లోడ్ అనుకరించండి",
    slipFall: "జారిపడటం గుర్తించబడింది"
  },
  mr: {
    arenaControl: "अरीना नियंत्रण केंद्र",
    fanCompanion: "फॅन सोबती ॲप",
    analytics: "आढावा आणि विश्लेषण",
    commandTitle: "इस्टॅडिओ अझ्टेका कमांड",
    liveBroadcast: "थेट प्रक्षेपण",
    gamedayMode: "सामन्याचा दिवस",
    recentIntercom: "अलीकडील इंटरकॉम नोंद",
    activeFans: "सक्रिय चाहते: ८४,२१२",
    staffMesh: "स्टाफ मेश नेटवर्क: १,२०४",
    emergencyAlert: "हवामान आणीबाणी चेतावणी",
    vipArrival: "व्हीआयपी शिष्टमंडळ आगमन",
    metroMalfunction: "सामन्यानंतर मेट्रो बिघाड",
    stepFree: "पायऱ्या नसलेला सुलभ मार्ग",
    launchAr: "AR कॅमेरा मार्गदर्शक सुरू करा",
    simulateLoad: "84k लोड स्पाइक सिम्युलेट करा",
    slipFall: "घसरून पडणे आढळले"
  },
  ta: {
    arenaControl: "அரங்க கட்டுப்பாட்டு மையம்",
    fanCompanion: "ரசிகர் துணை செயலி",
    analytics: "கண்ணோட்டம் & பகுப்பாய்வு",
    commandTitle: "எஸ்டாடியோ அஸ்டெகா கமாண்ட்",
    liveBroadcast: "நேரடி ஒளிபரப்பு",
    gamedayMode: "போட்டி நாள் முறை",
    recentIntercom: "சமீபத்திய இண்டர்காம் பதிவு",
    activeFans: "செயலில் உள்ள ரசிகர்கள்: 84,212",
    staffMesh: "ஊழியர் மெஷ் நெட்வொர்க்: 1,204",
    emergencyAlert: "அவசர காலநிலை எச்சரிக்கை",
    vipArrival: "VIP குழு வருகை",
    metroMalfunction: "மெட்ரோ ரயில் பழுது",
    stepFree: "படி-இல்லாத அணுகல் பாதை",
    launchAr: "AR கேமராவை இயக்கு",
    simulateLoad: "84k சுமை உருவகப்படுத்து",
    slipFall: "வழுக்கி விழுதல் கண்டறியப்பட்டது"
  },
  ur: {
    arenaControl: "ارینا کنٹرول سینٹر",
    fanCompanion: "فین ساتھی ایپ",
    analytics: "جائزہ اور تجزیات",
    commandTitle: "ایسٹاڈیو ازٹیکا کمانڈ",
    liveBroadcast: "لائیو نشریات",
    gamedayMode: "کھیل کا دن",
    recentIntercom: "حالیہ انٹرکام لاگ",
    activeFans: "فعال مداح: 84,212",
    staffMesh: "اسٹاف میش نیٹ ورک: 1,204",
    emergencyAlert: "ہنگامی موسم کا الرٹ",
    vipArrival: "VIP وفد کی آمد",
    metroMalfunction: "میچ کے بعد میٹرو کی خرابی",
    stepFree: "اسٹیپ فری رسائی کا راستہ",
    launchAr: "AR کیمرہ شروع کریں",
    simulateLoad: "84k لوڈ اسپائک کی نقل کریں",
    slipFall: "پھسل کر گرنے کی نشاندہی"
  },
  gu: {
    arenaControl: "એરેના કંટ્રોલ સેન્ટર",
    fanCompanion: "ફેન સાથી એપ્લિકેશન",
    analytics: "વિહંગાવલોકન અને વિશ્લેષણ",
    commandTitle: "એસ્ટાડિઓ એઝટેકા કમાન્ડ",
    liveBroadcast: "લાઈવ પ્રસારણ",
    gamedayMode: "રમતના દિવસ મોડ",
    recentIntercom: "તાજેતરના ઇન્ટરકોમ લોગ",
    activeFans: "સક્રિય ચાહકો: ૮૪,૨૧૨",
    staffMesh: "સ્ટાફ મેશ નેટવર્ક: ૧,૨૦૪",
    emergencyAlert: "કટોકટી હવામાન ચેતવણી",
    vipArrival: "VIP પ્રતિનિધિમંડળ આગમન",
    metroMalfunction: "મેચ પછી મેટ્રો નિષ્ફળતા",
    stepFree: "પગથિયાં-મુક્ત સુલભ માર્ગ",
    launchAr: "AR કેમેરા માર્ગદર્શક શરૂ કરો",
    simulateLoad: "84k લોડ સ્પાઇક સિમ્યુલેટ કરો",
    slipFall: "લપસી પડવાનું શોધી કઢાયું"
  },
  kn: {
    arenaControl: "ಅರೆನಾ ನಿಯಂತ್ರಣ ಕೇಂದ್ರ",
    fanCompanion: "ಅಭಿಮಾನಿ ಒಡನಾಡಿ",
    analytics: "ಅವಲೋಕನ ಮತ್ತು ವಿಶ್ಲೇಷಣೆ",
    commandTitle: "ಎಸ್ಟಾಡಿಯೊ ಅಜ್ಟೆಕಾ ಕಮಾಂಡ್",
    liveBroadcast: "ನೇರ ಪ್ರಸಾರ",
    gamedayMode: "ಗೇಮ್‌ಡೇ ಮೋಡ್",
    recentIntercom: "ಇಂಟರ್‌ಕಾಮ್ ಲಾಗ್‌ಗಳು",
    activeFans: "ಸಕ್ರಿಯ ಅಭಿಮಾನಿಗಳು: 84,212",
    staffMesh: "ಸಿಬ್ಬಂದಿ ಮೆಶ್ ಜಾಲ: 1,204",
    emergencyAlert: "ತುರ್ತು ಹವಾಮಾನ ಎಚ್ಚರಿಕೆ",
    vipArrival: "VIP ನಿಯೋಗದ ಆಗಮನ",
    metroMalfunction: "ಮೆಟ್ರೋ ವೈಫಲ್ಯ",
    stepFree: "ಮೆಟ್ಟಿಲು-ರಹಿತ ಸುಲಭ ಮಾರ್ಗ",
    launchAr: "AR ಕ್ಯಾಮೆರಾ ಪ್ರಾರಂಭಿಸಿ",
    simulateLoad: "84k ಲೋಡ್ ಸಿಮ್ಯುಲೇಟ್ ಮಾಡಿ",
    slipFall: "ಜಾರಿ ಬೀಳುವಿಕೆ ಪತ್ತೆಯಾಗಿದೆ"
  },
  ml: {
    arenaControl: "അരീന കൺട്രോൾ സെന്റർ",
    fanCompanion: "ഫാൻ കമ്പാനിയൻ",
    analytics: "അവലോകനവും അനലിറ്റിക്സും",
    commandTitle: "എസ്റ്റാഡിയോ ആസ്ടെക്ക കമാൻഡ്",
    liveBroadcast: "തത്സമയ സംപ്രേഷണം",
    gamedayMode: "ഗെയിംഡേ മോഡ്",
    recentIntercom: "സമീപകാല ഇന്റർകോം ലോഗ്",
    activeFans: "സജീവ ഫാൻസ്: 84,212",
    staffMesh: "സ്റ്റാഫ് മെഷ് നെറ്റ്‌വർക്ക്: 1,204",
    emergencyAlert: "അടിയന്തിര കാലാവസ്ഥാ മുന്നറിയിപ്പ്",
    vipArrival: "വി.ഐ.പി സംഘത്തിന്റെ വരവ്",
    metroMalfunction: "മെട്രോ തകരാറുകൾ",
    stepFree: "പടിയില്ലാത്ത സുഗമമായ പാത",
    launchAr: "AR ക്യാമറ വഴി കാട്ടി ആരംഭിക്കുക",
    simulateLoad: "84k ലോഡ് സ്പൈക്ക് സിമുലേറ്റ് ചെയ്യുക",
    slipFall: "വഴുതി വീഴുന്നത് കണ്ടെത്തി"
  },
  or: {
    arenaControl: "ଆରେନା ନିୟନ୍ତ୍ରଣ କେନ୍ଦ୍ର",
    fanCompanion: "ଫ୍ୟାନ୍ ସହଯୋଗୀ",
    analytics: "ସମୀକ୍ଷା ଏବଂ ବିଶ୍ଳେଷଣ",
    commandTitle: "ଏଷ୍ଟାଡିଓ ଆଜଟେକା କମାଣ୍ଡ",
    liveBroadcast: "ସିଧା ପ୍ରସାରଣ",
    gamedayMode: "ଖେଳ ଦିନ ମୋଡ୍",
    recentIntercom: "ସାମ୍ପ୍ରତିକ ଇଣ୍ଟରକମ୍ ଲଗ୍",
    activeFans: "ସକ୍ରିୟ ପ୍ରଶଂସକ: ୮୪,୨୧୨",
    staffMesh: "କର୍ମଚାରୀ ମେଶ୍ ନେଟୱର୍କ: ୧,୨୦୪",
    emergencyAlert: "ଜରୁରୀକାଳୀନ ପାଣିପାଗ ସତର୍କତା",
    vipArrival: "VIP ପ୍ରତିନିଧି ଦଳ ଆଗମନ",
    metroMalfunction: "ମ୍ୟାଚ୍ ପରେ ମେଟ୍ରୋ ବିଭ୍ରାଟ",
    stepFree: "ସୋପାନ-ମୁକ୍ତ ସୁଗମ ପଥ",
    launchAr: "AR କ୍ୟାମେରା ମାର୍ଗଦର୍ଶକ ଆରମ୍ଭ କରନ୍ତୁ",
    simulateLoad: "84k ଲୋଡ୍ ଅନୁକରଣ କରନ୍ତୁ",
    slipFall: "ଖସିପଡିବା ଚିହ୍ନଟ ହୋଇଛି"
  },
  pa: {
    arenaControl: "ਅਰੀਨਾ ਕੰਟਰੋਲ ਕੇਂਦਰ",
    fanCompanion: "ਪ੍ਰਸ਼ੰਸਕ ਸਾਥੀ ਐਪ",
    analytics: "ਸਮੀਖਿਆ ਅਤੇ ਵਿਸ਼ਲੇਸ਼ਣ",
    commandTitle: "ਏਸਟਾਡੀਓ ਐਜ਼ਟੇਕਾ ਕਮਾਂਡ",
    liveBroadcast: "ਲਾਈਵ ਪ੍ਰਸਾਰਣ",
    gamedayMode: "ਗੇਮ ਡੇ ਮੋਡ",
    recentIntercom: "ਹਾਲੀਆ ਇੰਟਰਕਾਮ ਲੌਗ",
    activeFans: "ਸਰਗਰਮ ਪ੍ਰਸ਼ੰਸਕ: 84,212",
    staffMesh: "ਸਟਾਫ ਮੈਸ਼ ਨੈੱਟਵਰਕ: 1,204",
    emergencyAlert: "ਹੰਗਾਮੀ ਮੌਸਮ ਚੇਤਾਵਨੀ",
    vipArrival: "VIP ਵਫ਼ਦ ਦੀ ਆਮਦ",
    metroMalfunction: "ਮੈਚ ਤੋਂ ਬਾਅਦ ਮੈਟਰੋ ਖ਼ਰਾਬ",
    stepFree: "ਪੌੜੀ-ਮੁਕਤ ਪਹੁੰਚਯੋਗ ਮਾਰਗ",
    launchAr: "AR ਕੈਮਰਾ ਮਾਰਗਦਰਸ਼ਕ ਚਾਲੂ ਕਰੋ",
    simulateLoad: "84k ਲੋਡ ਸਪਾਈਕ ਸਿਮੂਲੇਟ ਕਰੋ",
    slipFall: "ਤਿਲਕ ਕੇ ਡਿੱਗਣਾ ਪਛਾਣਿਆ ਗਿਆ"
  },
  as: {
    arenaControl: "এৰিনা নিয়ন্ত্ৰণ কেন্দ্ৰ",
    fanCompanion: "ফেন সংগী",
    analytics: "অৱলোকন আৰু বিশ্লেষণ",
    commandTitle: "এষ্টাদিঅ' এজটেকা কমাণ্ড",
    liveBroadcast: "সজীৱ সম্প্ৰচাৰ",
    gamedayMode: "খেলৰ দিন মোড",
    recentIntercom: "শেহতীয়া ইন্টাৰকম লগ",
    activeFans: "সক্ৰিয় ফেন: ৮৪,২১২",
    staffMesh: "কৰ্মচাৰী জাল নেটৱৰ্ক: ১,২০৪",
    emergencyAlert: "জৰুৰীকালীন বতৰৰ সতৰ্কতা",
    vipArrival: "ভিআইপি প্ৰতিনিধিৰ আগমন",
    metroMalfunction: "মেট্ৰ' বিভ্ৰাট",
    stepFree: "খটখটি অবিহনে সুগম পথ",
    launchAr: "AR কেমেৰা ৱেফাইণ্ডাৰ মুকলি কৰক",
    simulateLoad: "84k লোড স্পাইক সিমুলেট কৰক",
    slipFall: "পিছলি পৰা চিনাক্ত কৰা হৈছে"
  },
  ma: {
    arenaControl: "एरिना नियंत्रण केंद्र",
    fanCompanion: "प्रशंसक सोबती",
    analytics: "अवलोकन आ विश्लेषण",
    commandTitle: "एस्टाडियो एज्टेका कमांड",
    liveBroadcast: "लाइव प्रसारण",
    gamedayMode: "मैच दिवस मोड",
    recentIntercom: "हालक इंटरकॉम लॉग",
    activeFans: "सक्रिय दर्शक: 84,212",
    staffMesh: "स्टाफ मेश नेटवर्क: 1,204",
    emergencyAlert: "मौसम आपातकालीन चेतावनी",
    vipArrival: "वीआईपी शिष्टमंडल आगमन",
    metroMalfunction: "मेट्रो सेवा बंद",
    stepFree: "पायदान-रहित सुगम मार्ग",
    launchAr: "AR कैमरा मार्गदर्शक शुरू करू",
    simulateLoad: "84k लोड स्पाइक के अनुकरण करू",
    slipFall: "घिसल क खसबाक पता लागल"
  },
  sa: {
    arenaControl: "क्रीडाङ्गण नियन्त्रण केन्द्रम्",
    fanCompanion: "प्रशंसक सहचरः",
    analytics: "अवलोकनं विश्लेषणञ्च",
    commandTitle: "एस्टाडियो एज्टेका नियन्त्रणम्",
    liveBroadcast: "सजीवप्रसारणम्",
    gamedayMode: "क्रीडादिवस विधिः",
    recentIntercom: "नूतन संवाद सूचिका",
    activeFans: "सक्रिय प्रयोक्तारः: ८४,२१२",
    staffMesh: "कर्मचारि जालतन्त्रम्: १,२०४",
    emergencyAlert: "आपत्कालीन ऋतु चेतावनी",
    vipArrival: "विशिष्ट शिष्टमण्डल आगमनम्",
    metroMalfunction: "मेट्रोयान विच्छेदः",
    stepFree: "ಸೋಪಾನರಹಿತ ಮಾರ್ಗಃ",
    launchAr: "एआर छायाचित्रक मार्गदर्शक आरभ्यताम्",
    simulateLoad: "84k भार स्पाइक अनुकरणं कुरु",
    slipFall: "स्खलनपतन ज्ञानम्"
  },
  ks: {
    arenaControl: "ایرینا کنٹرول سینٹر",
    fanCompanion: "فین ساتھی",
    analytics: "خلاصہ تہِ تجزیہ",
    commandTitle: "ایسٹاڈیو ازٹیکا کمانڈ",
    liveBroadcast: "براہ راست نشریات",
    gamedayMode: "کھیلُن دۆہ",
    recentIntercom: "حالیہ انٹرکام لاگ",
    activeFans: "مداح: 84,212",
    staffMesh: "سٹاف نیٹ ورک: 1,204",
    emergencyAlert: "موسم الرٹ",
    vipArrival: "وی آئی پی وفد آمد",
    metroMalfunction: "میٹروبند",
    stepFree: "سیڑھی بغیر آسان راستہ",
    launchAr: "AR کیمرہ چلاؤ",
    simulateLoad: "84k لوڈ بناؤ",
    slipFall: "پھسلنا پتا چلا"
  },
  ne: {
    arenaControl: "एरिना नियन्त्रण केन्द्र",
    fanCompanion: "प्रशंसक साथी",
    analytics: "अवलोकन र विश्लेषण",
    commandTitle: "एस्टाडियो एज्टेका कमाण्ड",
    liveBroadcast: "प्रत्यक्ष प्रसारण",
    gamedayMode: "खेलको दिन मोड",
    recentIntercom: "भर्खरको इन्टरकम लग",
    activeFans: "सक्रिय प्रशंसक: ८४,२१२",
    staffMesh: "कर्मचारी मेश नेटवर्क: १,२०४",
    emergencyAlert: "आकस्मिक मौसम चेतावनी",
    vipArrival: "VIP प्रतिनिधिमण्डल आगमन",
    metroMalfunction: "मेट्रो सेवा अवरुद्ध",
    stepFree: "सिँढी-मुक्त सुलभ मार्ग",
    launchAr: "AR क्यामेरा मार्गदर्शक खोल्नुहोस्",
    simulateLoad: "84k लोड स्पाइक सिमुलेट गर्नुहोस्",
    slipFall: "चिप्लिएर लडेको पत्ता लाग्यो"
  },
  ko: {
    arenaControl: "अरीना नियंत्रण केंद्र",
    fanCompanion: "प्रशंसक सोबती",
    analytics: "आढावो आ विश्लेषण",
    commandTitle: "इस्टॅडिओ अझ्टेका कमाण्ड",
    liveBroadcast: "थेट प्रक्षेपण",
    gamedayMode: "खेळाचो दीस",
    recentIntercom: "नूतन इंटरकॉम लॉग",
    activeFans: "सक्रिय चाहते: ८४,२१२",
    staffMesh: "स्टाफ मेश नेटवर्क: १,२०४",
    emergencyAlert: "हवामान आणीबाणी शिटकावणी",
    vipArrival: "VIP शिष्टमंडळ येवप",
    metroMalfunction: "मेट्रो सेवा बंद",
    stepFree: "पायऱ्या विरहीत सुलभ मार्ग",
    launchAr: "AR कॅमेरा चालू करा",
    simulateLoad: "84k लोड स्पाइक सिमुलेट करा",
    slipFall: "घसरून पडप मेळ्ळें"
  },
  sd: {
    arenaControl: "ارينا ڪنٽرول سينٽر",
    fanCompanion: "فيس ساتي",
    analytics: "جائزو ۽ تجزيو",
    commandTitle: "ايسٽاڊيو ازٽيڪا ڪمانڊ",
    liveBroadcast: "لائيوز نشر",
    gamedayMode: "کيل جو ڏينهن",
    recentIntercom: "تازو انٽرڪام لاگ",
    activeFans: "مداح: 84,212",
    staffMesh: "اسٽاف نيٽ ورڪ: 1,204",
    emergencyAlert: "موسم الرٽ",
    vipArrival: "وي آءِ پي وفد جي آمد",
    metroMalfunction: "ميٽرو خراب",
    stepFree: "سڌو سنئون لنگهه",
    launchAr: "AR ڪيمرا کوليو",
    simulateLoad: "84k لوڊ وڌايو",
    slipFall: "ڪرڻ جي نشاندهي"
  },
  dog: {
    arenaControl: "एरिना नियंत्रण केंद्र",
    fanCompanion: "प्रशंसक साथी",
    analytics: "अवलोकन ते विश्लेषण",
    commandTitle: "एस्टाडियो एज्टेका कमांड",
    liveBroadcast: "लाइव प्रसारण",
    gamedayMode: "मैच दा दिन",
    recentIntercom: "नुआ इंटरकॉम लॉग",
    activeFans: "सक्रिय प्रशंसक: ८४,२१२",
    staffMesh: "स्टाफ मेश नेटवर्क: १,२०४",
    emergencyAlert: "आपातकालीन मौसम चेतावनी",
    vipArrival: "वीआईपी प्रतिनिधिमंडल आगमन",
    metroMalfunction: "मेट्रो खराबी",
    stepFree: "पौड़ी-रहित सुलभ मार्ग",
    launchAr: "एआर कैमरा मार्गदर्शक शुरू करो",
    simulateLoad: "84k लोड स्पाइक सिमुलेट करो",
    slipFall: "फिसलने ते डिगने दा पता लग्गेया"
  },
  mni: {
    arenaControl: "অ্যারেনা কন্ত্রোল সেন্তর",
    fanCompanion: "ফেন শৌগৎপগী খুৎলায়",
    analytics: "য়েংশিনবা অমসুং নৈনবা",
    commandTitle: "এস্তাদিও অজেতেকা কমান্দ",
    liveBroadcast: "লাইভ ফোঙবা",
    gamedayMode: "শেল্লোন নুমিৎ মোদ",
    recentIntercom: "অনৌবা ইন্তরকম রেজিস্তর",
    activeFans: "ফেন মশিং: ৮৪,২১২",
    staffMesh: "শিন্মী মেশ লুপ: ১,২০৪",
    emergencyAlert: "অকন্নবা নুংশিৎ চেকশিনৱা",
    vipArrival: "VIP কাংবুনা লাকপা",
    metroMalfunction: "মেত্রো খুৎলায় থিংজিলকপা",
    stepFree: "খঙলৈ লৈতবা এপ্রোচ লেন",
    launchAr: "AR ক্যামেরা থোং হাঙ্গৎলু",
    simulateLoad: "84k পোৎলুম সিমুলেত তৌ",
    slipFall: "লপসিদুনা তারকপা খঙলে"
  },
  bod: {
    arenaControl: "འགྲན་རྭ་ཚंटའཛིན་ལྟེ་གནས།",
    fanCompanion: "རྒྱབ་སྐྱོར་པ་རོགས་རེག",
    analytics: "སྤྱི་ལྟ་དང་དབྱེ་ཞིབ།",
    commandTitle: "ཨེ་སི་ཊ་ཌིའོ་ཨེཛ་ཊེ་ཀ་བཀོད་འདོམས།",
    liveBroadcast: "ཐད་གཏོང་།",
    gamedayMode: "རྩེད་མོའི་ཉིན་མོའི་ལམ།",
    recentIntercom: "ཉེ་བའི་བརྡ་འཕྲིན་ཟིན་ཐོ།",
    activeFans: "རྩེད་དགའ་བ།: ༨༤,༢༡༢",
    staffMesh: "ལས་བཟོའི་དྲ་རྒྱ།: ༡,༢༠༤",
    emergencyAlert: "ཛ་དྲག་གནམ་གཤིས་ཉེན་བརྡ།",
    vipArrival: "སྐུ་མགྲོན་གཟིགས་སྐོར་ཕེབས་པ།",
    metroMalfunction: "ས་འོག་མེ་འཁོར་ལམ་ཆག",
    stepFree: "སྐས་རིམ་མེད་པའི་བདེ་ལམ།",
    launchAr: "ARཔར་ཆས་སྣེ་ཤན་ཕྱེ་བ།",
    simulateLoad: "84kཐེག་ཚད་ལད་ཟླས།",
    slipFall: "རྡིབ་ནས་ལྷུང་བ་གསལ་བ།"
  },
  sat: {
    arenaControl: "ᱮᱨᱮᱱᱟ ᱠᱚᱱᱴᱨᱚᱞ ᱥᱮᱱᱴᱟᱨ",
    fanCompanion: "ᱯᱷᱮᱱ ᱥᱚᱦᱮᱫ ᱮᱯ",
    analytics: "ᱥᱚᱢᱤᱠᱷᱟ ᱟᱨ ᱵᱤᱥᱞᱮᱥᱚᱱ",
    commandTitle: "ᱮᱥᱴᱟᱰᱤᱭᱳ ᱮᱡᱴᱮᱠᱟ ᱠᱚᱢᱟᱱᱰ",
    liveBroadcast: "ᱥᱚᱡᱷᱮ ᱯᱨᱚᱥᱟᱨᱚᱱ",
    gamedayMode: "ᱠᱷᱮᱞ ᱢᱟᱦᱟᱸ ᱢᱳᱰ",
    recentIntercom: "ᱱᱟᱣᱟ ᱤᱱᱴᱟᱨᱠᱚᱢ ᱞᱚᱜ",
    activeFans: "ᱥᱟᱹᱠᱨᱤᱭ ᱯᱷᱮᱱ: ᱘᱔,᱒᱑᱒",
    staffMesh: "ᱠᱟᱹᱢᱤᱭᱟᱹ ᱢᱮᱥ ᱱᱮᱴᱣᱚᱨᱠ: ᱑,᱒᱐᱔",
    emergencyAlert: "ᱟᱹᱰᱤ ᱞᱟᱹᱠᱛᱤᱭᱟᱱ ᱦᱚᱭᱦᱤᱥᱤᱫ ᱪᱮᱛᱟᱣᱱᱤ",
    vipArrival: "VIP ᱫᱚᱞ ᱥᱮᱴᱮᱨ",
    metroMalfunction: "ᱢᱮᱴᱨᱚ ᱵᱟᱹᱲᱤᱡ",
    stepFree: "ᱥᱤᱰᱷᱤ ᱵᱮᱜᱚᱨ ᱥᱩᱜᱚᱲ ᱦᱚᱨ",
    launchAr: "AR ᱠᱮᱢᱮᱨᱟ ᱩᱫᱩᱜ ᱦᱚᱨ ᱡᱷᱤᱡ",
    simulateLoad: "84k ᱞᱳᱰ ᱥᱤᱢᱩᱞᱮᱴ",
    slipFall: "ᱞᱟ পিছᱞᱟᱣ ᱧᱟᱢ ᱮᱱᱟ"
  }
};
